services:
  - type: web
    name: sanjeevani-backend
    env: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: sanjeevani-frontend
    env: static
    rootDir: web-frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    envVars:
      - key: VITE_BACKEND_URL
        value: "https://sanjeeeveni.onrender.com"
