"""
Mobile Authentication API Routes
- Doctor login (credentials from HMS admin)
- Driver login (credentials from HMS admin)
- Helper self-registration
- Helper login
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import Session, select
import uuid

from database import get_session
from app.models.hospital_models import Doctor, Driver, Helper, Hospital
from app.schemas.mobile_auth_schemas import (
    DoctorLoginRequest, DriverLoginRequest,
    HelperRegisterRequest, HelperLoginRequest,
    MobileAuthResponse
)
from app.auth.security import verify_password, get_password_hash, create_access_token

from sqlalchemy import func

router = APIRouter(prefix="/mobile", tags=["Mobile App Authentication"])


# ──────────────────────────────────────────
# 👨‍⚕️ DOCTOR LOGIN (credentials from HMS)
# ──────────────────────────────────────────
@router.post("/login/doctor", response_model=MobileAuthResponse)
def login_doctor(payload: DoctorLoginRequest, db: Session = Depends(get_session)):
    """
    Doctor logs in using email, contact number, or doctor ID + password.
    Credentials are generated by Hospital Management Admin — no self-registration.
    """
    identifier = payload.identifier.strip()
    ident_lower = identifier.lower()

    # Match by email (case-insensitive), contact_number, or doctor ID (case-insensitive)
    all_doctors = db.exec(select(Doctor)).all()
    doctor = None
    for d in all_doctors:
        if (d.email and d.email.lower() == ident_lower) or \
           (d.contact_number and d.contact_number.strip() == identifier) or \
           (d.id and d.id.lower() == ident_lower):
            doctor = d
            break

    if not doctor:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"No doctor account found matching '{identifier}'. Check your email/phone or register doctor in Hospital Admin."
        )

    if not doctor.password_hash:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Doctor account has no password set. Contact your hospital admin to reset credentials."
        )

    if not verify_password(payload.password, doctor.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect password. Please try again or contact your hospital admin."
        )

    if not doctor.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Your doctor account is currently deactivated. Contact hospital admin."
        )

    # Resolve hospital name
    hospital = db.exec(select(Hospital).where(Hospital.id == doctor.hospital_id)).first()
    hospital_name = hospital.name if hospital else "Unknown Hospital"

    # Generate JWT
    token = create_access_token(data={
        "sub": doctor.id,
        "role": "doctor",
        "hospital_id": doctor.hospital_id
    })

    return MobileAuthResponse(
        success=True,
        token=token,
        role="doctor",
        user_id=doctor.id,
        user_name=doctor.name,
        hospital_id=doctor.hospital_id,
        hospital_name=hospital_name,
        specialization=doctor.specialization,
        contact_number=doctor.contact_number,
        email=doctor.email,
        shift_timing=doctor.shift_timing
    )


# ──────────────────────────────────────────
# 🚘 DRIVER LOGIN (credentials from HMS)
# ──────────────────────────────────────────
@router.post("/login/driver", response_model=MobileAuthResponse)
def login_driver(payload: DriverLoginRequest, db: Session = Depends(get_session)):
    """
    Driver logs in using contact number, email, or driver ID + password.
    Credentials are generated by Hospital Management Admin — no self-registration.
    """
    identifier = payload.identifier.strip()
    ident_lower = identifier.lower()

    all_drivers = db.exec(select(Driver)).all()
    driver = None
    for drv in all_drivers:
        if (drv.contact_number and drv.contact_number.strip() == identifier) or \
           (drv.email and drv.email.lower() == ident_lower) or \
           (drv.id and drv.id.lower() == ident_lower):
            driver = drv
            break

    if not driver:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail=f"No driver account found matching '{identifier}'. Check your phone/email or register driver in Hospital Admin."
        )

    if not driver.password_hash:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Driver account has no password set. Contact your hospital admin to reset credentials."
        )

    if not verify_password(payload.password, driver.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect password. Please try again or contact your hospital admin."
        )

    # Resolve hospital name
    hospital = db.exec(select(Hospital).where(Hospital.id == driver.hospital_id)).first()
    hospital_name = hospital.name if hospital else "Unknown Hospital"

    # Generate JWT
    token = create_access_token(data={
        "sub": driver.id,
        "role": "driver",
        "hospital_id": driver.hospital_id
    })

    return MobileAuthResponse(
        success=True,
        token=token,
        role="driver",
        user_id=driver.id,
        user_name=driver.name,
        hospital_id=driver.hospital_id,
        hospital_name=hospital_name,
        contact_number=driver.contact_number,
        email=driver.email,
        license_number=driver.license_number,
        badge_id=driver.id,
        shift_timing=driver.shift_timing
    )


# ──────────────────────────────────────────
# 🤝 HELPER SELF-REGISTRATION
# ──────────────────────────────────────────
@router.post("/register/helper", response_model=MobileAuthResponse, status_code=status.HTTP_201_CREATED)
def register_helper(payload: HelperRegisterRequest, db: Session = Depends(get_session)):
    """
    Community helper (ASHA worker, volunteer, paramedic) self-registers.
    Creates account with phone + password.
    """
    # Check if phone already registered
    existing = db.exec(
        select(Helper).where(Helper.phone == payload.phone.strip())
    ).first()

    if existing:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"A helper account with phone '{payload.phone}' is already registered. Please login instead."
        )

    helper_id = f"HLP-{uuid.uuid4().hex[:8].upper()}"
    pwd_hash = get_password_hash(payload.password)

    helper = Helper(
        id=helper_id,
        name=payload.name.strip(),
        phone=payload.phone.strip(),
        password_hash=pwd_hash,
        location=payload.location,
        role_type=payload.role_type,
        cert_id=payload.cert_id,
        skills=payload.skills,
    )

    db.add(helper)
    db.commit()
    db.refresh(helper)

    # Generate JWT
    token = create_access_token(data={
        "sub": helper.id,
        "role": "helper"
    })

    return MobileAuthResponse(
        success=True,
        token=token,
        role="helper",
        user_id=helper.id,
        user_name=helper.name,
        contact_number=helper.phone,
        location=helper.location,
        role_type=helper.role_type
    )


# ──────────────────────────────────────────
# 🤝 HELPER LOGIN
# ──────────────────────────────────────────
@router.post("/login/helper", response_model=MobileAuthResponse)
def login_helper(payload: HelperLoginRequest, db: Session = Depends(get_session)):
    """
    Helper logs in using phone + password.
    """
    phone = payload.phone.strip()

    helper = db.exec(
        select(Helper).where(Helper.phone == phone)
    ).first()

    if not helper:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="No helper account found with this phone number. Please register first."
        )

    if not verify_password(payload.password, helper.password_hash):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect password. Please try again."
        )

    if not helper.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Your helper account is currently deactivated."
        )

    # Generate JWT
    token = create_access_token(data={
        "sub": helper.id,
        "role": "helper"
    })

    return MobileAuthResponse(
        success=True,
        token=token,
        role="helper",
        user_id=helper.id,
        user_name=helper.name,
        contact_number=helper.phone,
        location=helper.location,
        role_type=helper.role_type
    )
